service: digiprod-service
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-add-api-key

custom: 
  apiKeys:
    - name: ${env:API_KEY_NAME}
      value: ${env:PRIVATE_API_KEY}
  
package: 
  individually: false

provider: 
  name: aws
  runtime: nodejs20.x
  memorySize: 2048
  timeout: 30
  stage: ${opt:stage, 'development'}
  region: ap-southeast-1

  apiGateway:
    apiKeySourceType: HEADER
    usagePlan: 
      quota: 
        limit: 1000000
        offset: 2
        period: MONTH
      throttle: 
        burstLimit: 300
        rateLimit: 100
    binaryMediaTypes:
      - 'multipart/form-data'
      - 'application/octet-stream'
      - 'application/*'
      - 'image/*'
      - 'video/*'
      - 'audio/*'

  ecr:
    images:
      app:
        path: ./
  
  environment:
    PORT: ${env:PORT}
    SECRET_ACCESS_AWS: ${env:SECRET_ACCESS_AWS}
    ACCESS_KEY_AWS: ${env:ACCESS_KEY_AWS}
    REGION_AWS: ${env:REGION_AWS}
    BUCKET_NAME_AWS: ${env:BUCKET_NAME_AWS}
    PRIVATE_API_KEY: ${env:PRIVATE_API_KEY}
    USAGE_PLAN_AWS: ${env:USAGE_PLAN_AWS}
    API_KEY_NAME: ${env:API_KEY_NAME}
    PARAMETER_STORE_NAMES: ${env:PARAMETER_STORE_NAMES}
    NODE_ENV: ${env:NODE_ENV}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRES_IN: ${env:JWT_EXPIRES_IN}

functions:
  main:
    image:
      name: app
      command:
        - dist/lambda.handler
    maximumRetryAttempts: 2
    events:
      # Root path
      - http:
          path: /
          method: GET
          private: false
          cors: true

      - http:
          path: /api/v1/{proxy+}
          method: ANY
          private: false 
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false