export const generalConstant = {
    SOMETHING_WENT_WRONG: 'Something went wrong, please try again later.',
    TYPE_NOT_FOUND: 'Type not found.',
    CATEGORY_NOT_FOUND: 'Category not found.',
    WITHDRAWAL_NOT_FOUND: 'Withdrawal not found.',
    USER_NOT_FOUND: 'User not found.',
    PRODUCT_NOT_FOUND: 'Product not found.',
    CURRICULUM_NOT_FOUND: 'Curriculum not found.',
    ORDER_NOT_FOUND: 'Order not found.',
    MIDTRANS_ERROR: 'Midtrans payment gateway error.',
    BALLANCE_NOT_ENOUGH: 'User balance is not enough for this transaction.',
    WITHDRAW_MESSAGE: 'Withdraw request received. Processing time is 1x24 hours.',
    PRODUCT_ALREADY_EXISTS: 'Product with this title already exists.',
    WITHDRAW_STATUS_INVALID: 'Withdraw status is invalid.',
    VOUCHER_NOT_FOUND: 'Voucher not found.',
    VOUCHER_EXPIRED: 'Voucher has expired.',
    VOUCHER_CODE_ALREADY_EXISTS: 'Voucher code already exists.',
    ECOURSE_SUB_MATERIAL_NOT_FOUND: 'Ecourse sub material not found.',
    RATING_ALREADY_EXISTS: 'You have already rated this product.',
}