name: Digprod Pipeline

on:
  push:
    branches:
      - master

jobs:
  prepare:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Verify PNPM Version
        run: pnpm --version

  deploy:
    needs: [prepare]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: 'pnpm'

      - name: Enable PNPM build scripts
        run: pnpm config set enable-pre-post-scripts true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Approve build
        run: pnpm approve-builds -g

      - name: Install Serverless CLI
        run: pnpm add -g serverless@v3 @nestjs/cli

      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_AWS }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY_AWS }}
          aws-region: ${{ secrets.REGION_AWS }}

      - name: Deploy to AWS
        env: 
          PORT: ${{ secrets.PORT }}
          SECRET_ACCESS_KEY_AWS: ${{ secrets.SECRET_ACCESS_KEY_AWS }}
          ACCESS_KEY_AWS: ${{ secrets.ACCESS_KEY_AWS }}
          REGION_AWS: ${{ secrets.REGION_AWS }}
          BUCKET_NAME_AWS: ${{ secrets.BUCKET_NAME_AWS }}
          PRIVATE_API_KEY: ${{ secrets.PRIVATE_API_KEY }}
          USAGE_PLAN_AWS: ${{ secrets.USAGE_PLAN_AWS }}
          API_KEY_NAME: ${{ secrets.API_KEY_NAME }}
          PARAMETER_STORES_NAMES: ${{ secrets.PARAMETER_STORES_NAMES }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          JWT_SCRET: ${{ secrets.JWT_SCRET }}
          JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
        run: pnpm run deploy
